spec:
   template:
      metadata:
         annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'app-python-service-account'
            vault.hashicorp.com/agent-inject-secret-app-python-secret.txt: 'internal/data/app-python/secret'