apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app-python
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: hugowea123/devops-labs-py
        ports:
        - containerPort: 5000