name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
     
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt
     
      - name: Linter
        run: pylint app_python/app.py
     
      - name: Run tests
        run: python -m unittest app_python/test_app.py
     
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Build Docker image
        run: |
          cd app_python
          docker build -t hugowea/devops-py-app-image:latest -f Dockerfile .
          
      - name: Push Docker Image
        run: |
          docker push hugowea/devops-py-app-image:latest
          cd ..